env:
  global:
  - JRUBY_OPTS="-Xcli.debug=true --debug"
  - CC_TEST_REPORTER_ID=a70bbb113a91b512f783fa152f252f89e86fe746356d1c47c3f66c7023e4c072

before_script:
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- ./cc-test-reporter before-build

script:
- bundle exec rspec

after_script:
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

before_install:
- gem update --system
- gem install bundler

install:
- bundle install

bundler_args: --no-deployment --jobs 3 --retry 3

cache: bundler

language: ruby
sudo: false

rvm:
  # latest versions on travis-ci as of 2018.09.04
  - ruby-2.2.10
  - ruby-2.3.7
  - ruby-2.4.4
  - ruby-2.5.1
  - ruby-head
gemfile:
  - gemfiles/rails50.gemfile
  - gemfiles/rails51.gemfile
  - gemfiles/rails52.gemfile

matrix:
  allow_failures:
  - rvm: ruby-head
  fast_finish: true
  exclude:
  # ruby-2.2.10 tests on all versions
  # ruby-2.3.7 tests on all versions
  # ruby-2.4.4 tests on all versions
  # ruby-2.5.1 tests on all versions
  # ruby-head only tests on rails 5.2+
  - rvm: ruby-head
    gemfile: gemfiles/rails_5_0.gemfile
  - rvm: ruby-head
    gemfile: gemfiles/rails_5_1.gemfile
