language: ruby
#bundler_args: --without development
rvm:
  - 2.2.2
  - 2.2.7
  - 2.3.0
  - 2.3.4
gemfile:
  - gemfiles/rails30.gemfile
  - gemfiles/rails32.gemfile
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
